languageCode = "en"
languageName = "English"
displayName = ":us:"
isoCode = "en"
weight = 2
rtl = false

title = "Ivan Belyavtsev"
# logo = "img/logo.jpg"
description = "Sr Developer [@BIFIT](https://www.bifit.com/)"
copyright = "&copy; 2016 - 2023 Ivan Belyavtsev"

dateFormat = "2 January 2006"
timeFormat = "3:04 pm"

[author]
  name = "Ivan Belyavtsev"
  image = "img/author.jpg"
  headline = "Sr Developer @BIFIT"
  bio = "Sr Developer [@BIFIT](https://www.bifit.com/)"
  links = [
    { email = "mailto:djbelyak@gmail.com" },
    { github = "https://github.com/djbelyak/" },
    { telegram = "https://t.me/djbelyak" },
  ]
